# Site
name: "Pwutseltronics Jekyll theme"
description: "An enhanced version of the Mundana Jekyll theme"
logo:    'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'https://pwutseltronics.nl'
baseurl: ''
disqus:  pwutseltronics
email:   info@pwutseltronics.nl
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-purgecss

sass:
  style: expanded
css_dir: "assets/css"

authors:
    Pwuts:
      name:       Reinier
      site:       https://pwuts.nl
      avatar:     'assets/images/reinier-avatar.jpg'
      bio:        "Hi, my name is Reinier and I am the creator of Pwutseltronics"
      email:      reinier@pwutseltronics.nl
      twitter:    https://twitter.com/Pwuts1337
      gitlab:     https://gitlab.com/Pwuts
      github:     https://github.com/Pwuts

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Pwuts
      avatar: 'assets/images/reinier-avatar.jpg'

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [Gemfile, Gemfile.lock, docker-compose.yml, README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
